import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
const { library, config } = require('@fortawesome/fontawesome-svg-core');
import { fab } from "@fortawesome/free-brands-svg-icons"
import {fas} from "@fortawesome/free-solid-svg-icons"
import {far} from "@fortawesome/free-regular-svg-icons"
import styles from '../styles/Home.module.css'
import {ThemeProvider} from 'next-themes'
import Landing from './sections/Landing'
library.add(fas,fab)

// library.add(fab)


export default function Home() {
  return (
    <ThemeProvider attribute='class'>
      <Head>
      <title>|| Khan Afif Farhan-Web developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='md:mx-[118px] sm:mx-[50px] mx-[20px] mt-[90px] border-cyan-300 shadow-[#e8e8e8_0px_2px_2px_0px] dark:bg-red-600 '
      >
        <Landing />
        

        
      </main>
      </ThemeProvider>
  )
}
